services:
  tunnel7:
    build:
      tags:
        - tunnel7
    # image: ghcr.io/ichbinbekir/tunnel7:master
    image: tunnel7:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data

    # you can change json path
    # volumes:
    #   - ./data:/root/data
    # command: ["-t", "/root/data/tunnels.json"]
